version: "3.5"

services:

  front:
    build: front/
    ports:
      - 80:80
    volumes:
      - ./front/default.conf:/etc/nginx/conf.d/default.conf
      - ../log/front:/var/log/nginx
      - ../www:/www

  back:
    build: back/
    ports:
      - 9000:9000
    volumes:
      - ../log/back:/usr/local/var/log
      - ../www:/www
#      - back/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ../db:/var/lib/mysql
      - ../arh:/arh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD:password
